web:
  port: 8080
  metrics: true
  debug: true

database:
  uri: "postgresql://filehub:filehub@localhost:5432/filehub"

realm: "file-hub"

# AWS S3 configuration (optional)
# Uncomment and configure the following section to enable S3 storage
#s3:
#  endpoint: "https://s3.amazonaws.com"
#  region: "us-east-1"
#  access_key_id: "YOUR_ACCESS_KEY_ID"
#  secret_access_key: "YOUR_SECRET_ACCESS_KEY"
